export const responseJson = [
  {
    0: [
      {
        display_name: "Public Speaking",
        rating: "4.9;5;117",
        games_count: "5",
        category_name: "Communication",
        original_price: 10000,
        discounted_price: 8000,
        name: "Public Speaking - Learn",
        certificate_count: 1,
        num_classes: 24,
        min_age: 6,
        max_age: 10,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
      {
        display_name: "Public Speaking",
        rating: "4.5;5;100",
        games_count: "3",
        category_name: "Communication",
        original_price: 10000,
        discounted_price: 8000,
        name: "Public Speaking - Learn",
        certificate_count: 2,
        num_classes: 20,
        min_age: 11,
        max_age: 15,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
    ],
    1: [
      {
        display_name: "Stop Motion Animation",
        rating: "4.9;5;117",
        games_count: "5",
        category_name: "Visual Arts",
        original_price: 12000,
        discounted_price: 7000,
        name: "Stop Motion Animation-Learn",
        certificate_count: 1,
        num_classes: 24,
        min_age: 5,
        max_age: 9,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
      {
        display_name: "Stop Motion Animation",
        rating: "4.5;5;100",
        games_count: "3",
        category_name: "Visual Arts",
        original_price: 11000,
        discounted_price: 5000,
        name: "Stop Motion Animation-Discover",
        certificate_count: 2,
        num_classes: 20,
        min_age: 5,
        max_age: 9,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
      {
        display_name: "Stop Motion Animation",
        rating: "4.5;5;100",
        games_count: "3",
        category_name: "Visual Arts",
        original_price: 11000,
        discounted_price: 5000,
        name: "Stop Motion Animation-Discover",
        certificate_count: 2,
        num_classes: 20,
        min_age: 10,
        max_age: 15,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
    ],
    2: [
      {
        display_name: "Western Vocals",
        rating: "4.9;5;117",
        games_count: "5",
        category_name: "Music",
        original_price: 12000,
        discounted_price: 7000,
        name: "Western Vocals-Learn",
        certificate_count: 1,
        num_classes: 14,
        min_age: 6,
        max_age: 15,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
      {
        display_name: "Western Vocals",
        rating: "4.5;5;100",
        games_count: "3",
        category_name: "Music",
        original_price: 11000,
        discounted_price: 5000,
        name: "Western Vocals-Discover",
        certificate_count: 2,
        num_classes: 20,
        min_age: 6,
        max_age: 15,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
      {
        display_name: "Western Vocals",
        rating: "4.0;5;100",
        games_count: "8",
        category_name: "Music",
        original_price: 11000,
        discounted_price: 5000,
        name: "Western Vocals-Excel",
        certificate_count: 2,
        num_classes: 30,
        min_age: 6,
        max_age: 15,
        pitch:
          "Learn to create well-researched speeches, structure arguments, and prepare for rebuttals through grammar and interactive speaking activities",
        curriculum_outcomes: [
          "Understand the debate format of communications and it’s structure",
          "Practice micro-skills used in debate - stating opinion, effective opening and closing, rebuttal",
          "Learn to research and prepare for a debate",
          "Perform and compete with other students!",
        ],
      },
    ],
  },
];
